// packages/vue/src/components/uploader.vue
<template>
  <div class="uploader">
    <uploader-drop :multiple="multiple" :accept="accept">
      <span style="margin-right: 6px">Drop file here or</span>
      <uploader-btn> click to upload </uploader-btn>
    </uploader-drop>
    <slot v-bind:fileList="files">
      <uploader-list :file-list="files">
        <template v-slot="slotProps">
          <uploader-file :file="slotProps.file"></uploader-file>
        </template>
      </uploader-list>
    </slot>
  </div>
</template>

<script>
import Uploader from '@tinyuploader/sdk'
import UploaderDrop from './uploader-drop.vue'
import UploaderBtn from './uploader-btn.vue'
import UploaderList from './uploader-list.vue'
import UploaderFile from './uploader-file.vue'

const Events = Uploader.Events

export default {
  components: {
    UploaderDrop,
    UploaderBtn,
    UploaderList,
    UploaderFile
  },
  provide() {
    return {
      instance: () => this.uploader
    }
  },
  props: {
    multiple: {
      type: Boolean,
      default: true
    },
    accept: {
      type: String,
      default: '*'
    },
    multiple: {
      type: Boolean,
      default: true
    },
    action: {
      type: String,
      default: ''
    },
    target: {
      type: String
    },
    withCredentials: {
      type: Boolean,
      default: true
    },
    headers: Object,
    data: Object,
    maxConcurrency: {
      type: Number,
      default: 6
    },
    chunkSize: {
      type: Number,
      default: 1024 * 4
    },
    autoUpload: {
      type: Boolean,
      default: true
    },
    name: {
      type: String,
      default: 'file'
    },
    customGenerateUid: {
      type: [Function, null],
      default: null
    },
    requestSucceed: {
      type: Function
    },
    maxRetries: {
      type: Number,
      default: 3
    },
    retryInterval: {
      type: Number,
      default: 1000
    },
    mergeRequest: {
      type: Function
    },
    fileList: {
      type: Array,
      default() {
        return []
      }
    }
  },
  data() {
    return {
      uploader: null,
      files: []
    }
  },
  watch: {
    fileList: {
      handler(fileList) {
        this.uploader = new Uploader({
          ...this._props,
          fileList: fileList
        })

        this.files = this.uploader.fileList

        this.uploader.on(Events.FilesAdded, (fileList) => {
          this.files = fileList
          this.$emit('onFilesAdded', fileList)
          this.$emit('onChange', fileList)
        })

        this.uploader.on(Events.AllFileSuccess, (fileList) => {
          this.files = fileList
          this.$emit('onAllFileSuccess', fileList)
          this.$emit('onChange', fileList)
        })

        this.uploader.on(Events.FileUploadSuccess, (file, fileList) => {
          this.files = fileList
          this.$emit('onFileUploadSuccess', file, fileList)
          this.$emit('onChange', fileList)
        })

        this.uploader.on(Events.FileSuccess, (file, fileList) => {
          this.files = fileList
          this.$emit('onFileSuccess', file, fileList)
          this.$emit('onChange', fileList)
        })

        this.uploader.on(Events.FileFail, (file, fileList) => {
          this.files = fileList
          this.$emit('onFileFail', file, fileList)
          this.$emit('onChange', fileList)
        })

        this.uploader.on(Events.FileUploadFail, (file, fileList) => {
          this.files = fileList
          this.$emit('onFileUploadFail', file, fileList)
        })

        this.uploader.on(Events.FileRemove, (file, fileList) => {
          this.files = fileList
          this.$emit('onFileRemove', file, fileList)
          this.$emit('onChange', fileList)
        })

        this.uploader.on(Events.FileProgress, (progress, file, fileList) => {
          this.files = fileList
          this.$emit('onFileProgress', file, fileList)
        })
      },
      immediate: true
    }
  },
  methods: {
    abort(file) {
      if (file) {
        this.uploader.remove(file)
        return
      }
      this.uploader.remove()
    },
    submit() {
      this.uploader.submit()
    }
  }
}
</script>

// packages/react/src/components/Uploader/index.jsx
import { useEffect, useState, forwardRef, useImperativeHandle } from 'react'
import PropTypes from 'prop-types'
import { UploaderContext } from '../UploaderContext'
import { create, Events } from '@tinyuploader/sdk'
import Drop from '../Drop'
import FileList from '../FileList'
import FileItem from '../FileItem'

const noop = () => {}

const Uploader = forwardRef((props, ref) => {
  const {
    fileList = [],
    accept = '*',
    multiple = true,
    chunkSize = 1024 * 1024 * 2,
    onExceed = noop,
    onFilesAdded = noop,
    onFileRemove = noop,
    onFileProgress = noop,
    onFileFail = noop,
    onFileUploadFail = noop,
    onFileUploadSuccess = noop,
    onFileSuccess = noop,
    onAllFileSuccess = noop,
    onFile = noop,
    onSuccess = noop,
    onChange = noop,
    onClick = noop
  } = props
  const [uploader, setUploader] = useState()
  const [files, setFiles] = useState([])

  const createInstance = () => {
    const instance = create({
      fileList: fileList,
      ...props,
      accept,
      multiple,
      chunkSize
    })

    setFiles([...instance.fileList])
    instance.on(Events.FileChange, (file, fileList) => {
      setFiles([...fileList])
    })

    instance.on(Events.Exceed, (files, fileList) => {
      setFiles([...fileList])
      onExceed(files, fileList)
    })

    instance.on(Events.FilesAdded, (fileList) => {
      setFiles([...fileList])
      onFilesAdded(fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileRemove, (file, fileList) => {
      setFiles([...fileList])
      onFileRemove(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileProgress, (progress, file, fileList) => {
      // setFiles([...fileList])
      onFileProgress(progress, file, fileList)
    })

    instance.on(Events.FileFail, (file, fileList) => {
      setFiles([...fileList])
      onFileFail(file, fileList)
      onFile(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileUploadFail, (file, fileList) => {
      setFiles([...fileList])
      onFileUploadFail(file, fileList)
      onFile(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileUploadSuccess, (file, fileList) => {
      setFiles([...fileList])
      onFileUploadSuccess(file, fileList)
    })

    instance.on(Events.FileSuccess, (file, fileList) => {
      setFiles([...fileList])
      onFileSuccess(file, fileList)
      onSuccess(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.AllFileSuccess, (fileList) => {
      setFiles([...fileList])
      onAllFileSuccess(fileList)
      onChange(fileList, null)
    })

    return instance
  }

  useEffect(() => {
    setUploader(createInstance())
  }, [])

  useImperativeHandle(
    ref,
    () => {
      return {
        remove() {
          uploader.remove()
        },
        submit() {
          uploader.submit()
        }
      }
    },
    [uploader]
  )

  return (
    <UploaderContext.Provider value={uploader}>
      <div ref={ref}>
        <Drop />
        {uploader && (
          <FileList fileList={files}>
            <FileItem onClick={onClick} />
          </FileList>
        )}
      </div>
    </UploaderContext.Provider>
  )
})

Uploader.displayName = 'Uploader'

Uploader.propTypes = {
  accept: PropTypes.string,
  multiple: PropTypes.bool,
  limit: PropTypes.number,
  fileList: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string,
      path: PropTypes.string
    })
  ),
  name: PropTypes.string,
  autoUpload: PropTypes.bool,
  action: PropTypes.string,
  fakeProgress: PropTypes.bool,
  withCredentials: PropTypes.bool,
  headers: PropTypes.object,
  data: PropTypes.object,
  withHash: PropTypes.bool,
  computedhashInWorker: PropTypes.bool,
  chunkSize: PropTypes.number,
  maxRetries: PropTypes.number,
  retryInterval: PropTypes.number,
  maxConcurrency: PropTypes.number,
  customGenerateUid: PropTypes.oneOf([null, PropTypes.func]),
  beforeAdd: PropTypes.func,
  beforeRemove: PropTypes.func,
  checkFileRequest: PropTypes.func,
  requestSucceed: PropTypes.func,
  mergeRequest: PropTypes.func,
  onExceed: PropTypes.func,
  onFilesAdded: PropTypes.func,
  onFileRemove: PropTypes.func,
  onFileProgress: PropTypes.func,
  onFileFail: PropTypes.func,
  onFileUploadFail: PropTypes.func,
  onFileUploadSuccess: PropTypes.func,
  onFileSuccess: PropTypes.func,
  onAllFileSuccess: PropTypes.func,
  onFile: PropTypes.func,
  onSuccess: PropTypes.func,
  onChange: PropTypes.func,
  onClick: PropTypes.func
}

export default Uploader
