// packages/react/src/components/Uploader/index.jsx
import { useEffect, useState, forwardRef } from 'react'
import PropTypes from 'prop-types'
import { UploaderContext } from '../UploaderContext'
import { create, Events } from '@tinyuploader/sdk'
import { Drop } from '../Drop'

const noop = () => {}

const Uploader = forwardRef((props, ref) => {
  const {
    defaultFileList = [],
    onInited = noop,
    onExceed = noop,
    onFilesAdded = noop,
    onFileRemove = noop,
    onFileProgress = noop,
    onFileFail = noop,
    onFileUploadFail = noop,
    onFileUploadSuccess = noop,
    onFileSuccess = noop,
    onAllFileSuccess = noop,
    onFile = noop,
    onSuccess = noop,
    onChange = noop
  } = props
  const [uploader, setUploader] = useState(null)
  const [files, setFiles] = useState([])

  const createInstance = () => {
    const instance = create({
      fileList: defaultFileList
    })

    setFiles([...instance.fileList])

    instance.on(Events.Inited, (fileList) => {
      setFiles([...fileList])
      onInited(fileList)
    })

    instance.on(Events.Exceed, (files, fileList) => {
      onExceed(files, fileList)
    })

    instance.on(Events.FilesAdded, (fileList) => {
      console.log(fileList)
      setFiles([...fileList])
      onFilesAdded(fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileRemove, (file, fileList) => {
      setFiles([...fileList])
      onFileRemove(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileProgress, (progress, file, fileList) => {
      setFiles([...fileList])
      onFileProgress(progress, file, fileList)
    })

    instance.on(Events.FileFail, (file, fileList) => {
      setFiles([...fileList])
      onFileFail(file, fileList)
      onFile(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileUploadFail, (file, fileList) => {
      setFiles([...fileList])
      onFileUploadFail(file, fileList)
      onFile(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.FileUploadSuccess, (file, fileList) => {
      setFiles([...fileList])
      onFileUploadSuccess(file, fileList)
    })

    instance.on(Events.FileSuccess, (file, fileList) => {
      setFiles([...fileList])
      onFileSuccess(file, fileList)
      onSuccess(file, fileList)
      onChange(fileList, null)
    })

    instance.on(Events.AllFileSuccess, (fileList) => {
      setFiles([...fileList])
      onAllFileSuccess(fileList)
      onChange(fileList, null)
    })

    return instance
  }

  useEffect(() => {
    setUploader(createInstance())
  }, [])

  return (
    <UploaderContext.Provider value={uploader}>
      <Drop />
      <div ref={ref}>
        {files.map((file) => {
          return (
            <div key={file.uid}>
              {file.name}
              {file.status}
              {file.progress}
            </div>
          )
        })}
      </div>
    </UploaderContext.Provider>
  )
})

Uploader.displayName = 'Uploader'

Uploader.propTypes = {
  defaultFileList: PropTypes.arrayOf(
    PropTypes.shape({
      name: PropTypes.string,
      path: PropTypes.string
    })
  ),
  onInited: PropTypes.func,
  onExceed: PropTypes.func,
  onFilesAdded: PropTypes.func,
  onFileRemove: PropTypes.func,
  onFileProgress: PropTypes.func,
  onFileFail: PropTypes.func,
  onFileUploadFail: PropTypes.func,
  onFileUploadSuccess: PropTypes.func,
  onFileSuccess: PropTypes.func,
  onAllFileSuccess: PropTypes.func,
  onFile: PropTypes.func,
  onSuccess: PropTypes.func,
  onChange: PropTypes.func
}

export default Uploader

// packages/vue-next/src/uploader.vue
<template>
  <div class="uploader">
    <uploader-drop>
      <upload-icon :size="40" color="#409eff" style="margin-bottom: 6px" />
      <div>
        <span>Drop file here or</span>
        <uploader-btn> click to upload </uploader-btn>
      </div>
    </uploader-drop>
    <slot :file-list="files">
      <uploader-list :file-list="files" v-slot="{ file }">
        <uploader-file :file="file"></uploader-file>
      </uploader-list>
    </slot>
  </div>
</template>

<script setup>
import { onMounted, ref, provide } from 'vue'
import { create, Callbacks } from '@tinyuploader/sdk'
import UploaderDrop from './components/uploader-drop.vue'
import UploaderBtn from './components/uploader-btn.vue'
import UploaderList from './components/uploader-list.vue'
import UploaderFile from './components/uploader-file.vue'
import UploadIcon from './icons/upload-icon.vue'
import { uploaderProps, uploaderEmits } from './uploader.js'

const props = defineProps(uploaderProps)
const emit = defineEmits(uploaderEmits)

const uploader = ref(null)
const files = ref([])

uploader.value = create(props)
files.value = uploader.value.fileList

provide('uploader', uploader)

onMounted(() => {
  uploader.value.on(Callbacks.Exceed, (files, fileList) => {
    emit('onExceed', files, fileList)
  })

  uploader.value.on(Callbacks.FilesAdded, (fileList) => {
    files.value = fileList
    emit('onFilesAdded', fileList)
  })

  uploader.value.on(Callbacks.FileChange, (file, fileList) => {
    files.value = fileList
    emit('onFileChange', fileList)
  })

  uploader.value.on(Callbacks.FileRemove, (file, fileList) => {
    files.value = fileList
    emit('onFileRemove', file, fileList)
  })

  uploader.value.on(Callbacks.FileProgress, (progress, file, fileList) => {
    emit('onFileProgress', progress, file, fileList)
  })

  uploader.value.on(Callbacks.FileFail, (file, fileList) => {
    files.value = fileList
    emit('onFileFail', file, fileList)
  })

  uploader.value.on(Callbacks.FileUploadFail, (file, fileList) => {
    files.value = fileList
    emit('onFileUploadFail', file, fileList)
  })

  uploader.value.on(Callbacks.FileUploadSuccess, (file, fileList) => {
    files.value = fileList
    emit('onFileUploadSuccess', file, fileList)
  })

  uploader.value.on(Callbacks.FileSuccess, (file, fileList) => {
    files.value = fileList
    emit('onFileSuccess', file, fileList)
  })

  uploader.value.on(Callbacks.AllFileSuccess, (fileList) => {
    files.value = fileList
    emit('onAllFileSuccess', fileList)
  })
})

const clear = () => {
  uploader.value.clear()
}

const submit = () => {
  uploader.value.submit()
}

defineExpose({
  clear,
  submit
})
</script>
